// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu76ELUumhSu191h2-KZmue_NomEGF8-4',
    appId: '1:847788296241:web:df12ea247a6156df166d10',
    messagingSenderId: '847788296241',
    projectId: 'clarity-c6f2c',
    authDomain: 'clarity-c6f2c.firebaseapp.com',
    storageBucket: 'clarity-c6f2c.firebasestorage.app',
    measurementId: 'G-3QPTBSS11B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD15cDO_C3jYqYKNxnY-4qiHIhANq_uZcc',
    appId: '1:847788296241:android:bb1c65aa348b01eb166d10',
    messagingSenderId: '847788296241',
    projectId: 'clarity-c6f2c',
    storageBucket: 'clarity-c6f2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmby3p34zNW44dTQdTnqtbPYsgOBeddqE',
    appId: '1:847788296241:ios:92beb572c028570d166d10',
    messagingSenderId: '847788296241',
    projectId: 'clarity-c6f2c',
    storageBucket: 'clarity-c6f2c.firebasestorage.app',
    iosBundleId: 'com.example.clarity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmby3p34zNW44dTQdTnqtbPYsgOBeddqE',
    appId: '1:847788296241:ios:ca2db5f8ceac49ce166d10',
    messagingSenderId: '847788296241',
    projectId: 'clarity-c6f2c',
    storageBucket: 'clarity-c6f2c.firebasestorage.app',
    iosBundleId: 'com.example.appForAdhd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu76ELUumhSu191h2-KZmue_NomEGF8-4',
    appId: '1:847788296241:web:0542c9fd724ca7fd166d10',
    messagingSenderId: '847788296241',
    projectId: 'clarity-c6f2c',
    authDomain: 'clarity-c6f2c.firebaseapp.com',
    storageBucket: 'clarity-c6f2c.firebasestorage.app',
    measurementId: 'G-HZN82XHEH7',
  );
}
