import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'views/to_do_list.dart';
import 'view_models/app_view_model.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure

/// Entry point of the application.
void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // Ensures Flutter engine is initialized for async code.
  // Initialize Firebase with platform-specific options.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  // Wrap the app with ChangeNotifierProvider for state management.
  runApp(
    ChangeNotifierProvider(
      create: (context) => AppViewModel(), // Provides AppViewModel to the widget tree.
      child: const MyApp(),
    ),
  );
}

/// Root widget of the app.
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    // UI code: MaterialApp sets up the app's navigation and theme
    return MaterialApp(
      title: 'Clarity', // UI code: App title in system UI
      home: const HomePage(), // UI code: Initial screen widget
    );
  }
}

/// Home page widget shown on app launch.
class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    // UI code: Scaffold provides the basic visual layout structure
    return Scaffold(
      appBar: AppBar(
        title: const Text('Clarity'), // UI code: AppBar title
        centerTitle: true, // UI code: Center the title in AppBar
      ),
      body: Center(
        // UI code: Center widget for vertical/horizontal alignment
        child: ElevatedButton(
          child: const Text('Tasks'), // UI code: Button label
          onPressed: () {
            // UI code: Navigation to ToDoList screen
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => const ToDoList()),
            );
          },
        ),
      ),
    );
  }
}
